### ISSUE TITLE
Minor bugs in HTML

### ISSUE THREAD

**Issue by NitinNair89** [GangsterTeam/twinkle#17]
This is from Firefox "View Source" option for the landing page.

![image](https://user-images.githubusercontent.com/16149618/47700424-6b3b5880-dc3c-11e8-9b5b-60d796c93b63.png)

Need to fix these:
* Extra `</body>` tag
* Extra `</div>` tag
* `<script>` tag to be moved before </body> tag

**Comment by Thilagavathi1** [comment]
Thanks @NitinNair89 .We already noted it,just now pushed the code.
