### ISSUE TITLE
 footer doesn't aligned properly in big screens

### ISSUE THREAD

**Issue by Thilagavathi1** [GangsterTeam/twinkle#2]

**Comment by NitinNair89** [comment]
What is the issue? I checked using CTRL+SHIFT+M in Firefox. Is the link 'source' to be aligned properly in smaller screens?

**Comment by Thilagavathi1** [comment]
> What is the issue? I checked using CTRL+SHIFT+M in Firefox. Is the link 'source' to be aligned properly in smaller screens?

@NitinNair89 Change the footer to be fixed.
![twinkle-fixed-footer](https://user-images.githubusercontent.com/16552447/47489507-6b1a1200-d864-11e8-865b-e4bc02c94c30.png)

**Comment by NitinNair89** [comment]
> 
> 
> > What is the issue? I checked using CTRL+SHIFT+M in Firefox. Is the link 'source' to be aligned properly in smaller screens?
> 
> @NitinNair89 Change the footer to be fixed.
> ![twinkle-fixed-footer](https://user-images.githubusercontent.com/16552447/47489507-6b1a1200-d864-11e8-865b-e4bc02c94c30.png)

Footer looks good in my Firefox and IE, will check in Chrome and mobile later. :)

**Comment by baladkb** [comment]
@mannski thanks for contribution 👍
