### ISSUE TITLE
UI issues in landing page

### ISSUE THREAD

**Issue by sygops** [GangsterTeam/twinkle#3]
Hi, please fix the landing page issues.
for your reference please check the screenshot,
![download 1](https://user-images.githubusercontent.com/16489082/47480020-97c22f80-d84c-11e8-8f4d-696f89be9d8d.png)

**Comment by HatboyWonder** [comment]
I can have a look. Please assign so other people know.

**Comment by baladkb** [comment]
> I can have a look. Please assign so other people know.

Ok, please give us PR.
Thanks :octocat:

**Comment by NitinNair89** [comment]
What is the issue with the nav? How do you want it to look?

**Comment by baladkb** [comment]
> What is the issue with the nav? How do you want it to look?
margin alignment issue @NitinNair89

**Comment by baladkb** [comment]
> > Hi, please fix the landing page issues.
> 
> The same height column issue can be solved by removing the use of **row-margin** class.
> Add **col** class to the responsive **table** element to fix the extra spaces
> 
> Should I send a PR?

Always welcome for PR! and we'll check internally. 

thanks :metal:

**Comment by NitinNair89** [comment]
> 
> 
> > What is the issue with the nav? How do you want it to look?
> > margin alignment issue @NitinNair89

Could you please explain? Is it the image? or the text beside image?

**Comment by Ri2parna** [comment]
is it fixed, or can I contribute?

**Comment by doghouch** [comment]
@Ri2parna It's already been merged...

**Comment by NitinNair89** [comment]
Please close this issue if requirements met 😃

**Comment by baladkb** [comment]
thanks @NitinNair89  💯 👍
