### ISSUE TITLE
Move JS code present in index.html to own JS file

### ISSUE THREAD

**Issue by NitinNair89** [GangsterTeam/twinkle#8]
I am not sure, if this can be seen as a issue, it's more of a suggestion to keep HTML page clean 👍 

Should we move JS code present inside index page to main or a separate JS file?

**Comment by baladkb** [comment]
Hi  @NitinNair89 
Oh ! That looks good to me. Could you please work on it and make a PR.

**Comment by luckywilliams** [comment]
Hi I have did it my branch but I am new on github how to push it on master branch I an using github site for editing.

**Comment by NitinNair89** [comment]
> 
> 
> Hi I have did it my branch but I am new on github how to push it on master branch I an using github site for editing.

Hi @luckywilliams 

Steps to contribute:
1 - FORK this repository (Ignore if already done)
2 - Do changes in your master branch and test 
3 - Create a pull request and use the "compare forks" option
4 - Review if your changes are visible
5 - Click the "Create Pull Request" button and wait for the repository owner to review your changes and take actions 

👍

**Comment by NitinNair89** [comment]
> 
> 
> Hi I have did it my branch but I am new on github how to push it on master branch I an using github site for editing.

Please take the latest index.html file so that there's no conflict 😃

**Comment by baladkb** [comment]
issue fixed, 
thanks @NitinNair89, @luckywilliams 👍  
FYI : https://github.com/GangsterTeam/twinkle/pull/14
